# Generated by Django 5.2 on 2025-04-26 05:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_libray_alter_tweet_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='libray',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photos/'),
        ),
    ]
